name: Swift

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  macOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['6.0']
    container:
      image: swift:${{ matrix.tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Test
      run: swift test --parallel --enable-code-coverage
